### ISSUE TITLE
Noticed Pubby missing machines/items/systems

### ISSUE THREAD

**Issue by CypressBz** [hrzntal/horizon#634]
## Round ID:

@MissFox0810 
Missing a universal grinder in xenobio
 I'll add more stuff as I find it.
 

## Testmerges:

N/A

## Reproduction:

N/A

**Comment by MissFox0810** [comment]
Fixed the missing grinder in last pubby or, I'll leave this open for 7 days in case more is found

**Comment by AsaiasWolffe** [comment]
![image](https://user-images.githubusercontent.com/59212063/148700171-7a5e91b6-beed-4da1-88a2-8af62d77ac15.png)
The turf the injector is on needs to be set to telecomms as well so it gets power. ultimately very minor as tcomms /shouldnt/ have a build up of bad gases but still an issue

**Comment by MissFox0810** [comment]
https://cdn.discordapp.com/attachments/797923789529939988/930250218186899486/unknown.png

**Comment by MissFox0810** [comment]
multiple lattices found in (120, 205, 3)

**Comment by atakiya** [comment]
as well in
- [ ] `129, 221, 3`
- [ ] `138, 205, 3`
- [ ] `146, 86, 3`
- [ ] `146, 84, 3`

**Comment by atakiya** [comment]
Missing organbox or organ printer for medical.

**Comment by MissFox0810** [comment]
moved to seprate issues with a tracking project board
